version: '2'

services:
  database:
    build: ./database
    ports:
      - 5433:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
  app:
    build: ./src
    ports:
      - 8001:8000
    volumes:
      - ./src/:/usr/src/
